#!/usr/bin/env python3
"""Generate the content cards for the demo video.

ONE GENERATOR, ONE PALETTE. Five separate hand-written HTML files would be five
copies of the same stylesheet, and this repository has a standing finding about
what copies do. The palette below is loop.svg's own, sampled from the file.

SELF-CONTAINED OUTPUT on purpose - the CSS is inlined into each card rather
than linked, because a capture run that depends on a second file resolving over
file:// is a capture run that can fail silently and ship an unstyled frame.

EVERY FIGURE ON THESE CARDS IS QUOTED WITH ITS DENOMINATOR AND ITS SOURCE.
That is not decoration: `docs/contest/DECISION-figures-2026-08-30.md` option 2
makes the denominator and the reader-acceptance count part of the claim, so a
card that showed a bare percentage would be publishing something the ruling
does not permit.

    python tools/capture/build-cards.py
"""
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
CARDS = HERE / "cards"

CSS = """
  :root{
    --ground:#14110F; --panel:#1E1A17; --line:#2A2521;
    --ink:#EDE8E2; --muted:#9A938B; --dim:#7C736B;
    --model:#E8933A; --code:#7FA0B0; --refuse:#C23B44;
  }
  *{margin:0;padding:0;box-sizing:border-box}
  html,body{width:1920px;height:1080px;overflow:hidden}
  body{background:var(--ground);color:var(--ink);
       font-family:"Segoe UI",Inter,"Helvetica Neue",Arial,sans-serif;
       -webkit-font-smoothing:antialiased;
       display:flex;flex-direction:column;justify-content:center;
       padding:0 110px}
  .kicker{font-family:ui-monospace,"Cascadia Mono",Consolas,monospace;
          font-size:24px;letter-spacing:.28em;text-transform:uppercase;
          color:var(--model);font-weight:600;margin-bottom:34px}
  h1{font-size:86px;line-height:1.06;font-weight:700;letter-spacing:-.026em;
     max-width:1620px}
  h1 .hot{color:var(--model)}
  h1 .no{color:var(--refuse)}
  .sub{font-size:34px;line-height:1.45;color:var(--muted);max-width:1500px;
       margin-top:34px}
  .sub b{color:var(--ink);font-weight:600}
  .mono{font-family:ui-monospace,"Cascadia Mono",Consolas,monospace}

  table{border-collapse:collapse;margin-top:44px;
        font-family:ui-monospace,Consolas,monospace;font-size:31px}
  th{text-align:left;color:var(--dim);font-weight:400;padding:0 44px 16px 0;
     border-bottom:1px solid var(--line);letter-spacing:.06em;font-size:24px;
     text-transform:uppercase}
  td{padding:17px 44px 17px 0;color:var(--muted);
     border-bottom:1px solid #221E1B;white-space:nowrap}
  tr.pool td{color:var(--ink);font-weight:600;font-size:34px}
  td .den{color:var(--dim);font-size:24px}
  .arrow{color:var(--model)}

  .steps{display:flex;gap:0;margin-top:56px;align-items:stretch}
  .step{flex:1;border-left:4px solid var(--line);padding:0 40px 0 32px}
  .step:first-child{border-left-color:var(--model)}
  .step .n{font-family:ui-monospace,Consolas,monospace;font-size:23px;
           color:var(--dim);letter-spacing:.2em;margin-bottom:16px}
  .step .t{font-size:42px;line-height:1.2;font-weight:600}
  .step .d{font-size:26px;line-height:1.45;color:var(--muted);margin-top:18px}

  ul{list-style:none;margin-top:44px}
  li{font-size:33px;line-height:1.5;color:var(--muted);padding:15px 0 15px 46px;
     border-bottom:1px solid #221E1B;position:relative}
  li:before{content:"\\25A0";position:absolute;left:0;color:var(--model);
            font-size:22px;top:22px}
  li b{color:var(--ink);font-weight:600}
  li .mono{font-size:29px;color:var(--code)}

  .src{position:absolute;left:110px;right:110px;bottom:62px;
       font-family:ui-monospace,Consolas,monospace;font-size:21px;
       color:var(--dim);border-top:1px solid var(--line);padding-top:22px}
  .src b{color:var(--muted);font-weight:400}
"""


def card(name, body, source):
    html = ("<!doctype html>\n<html lang=\"en\"><head><meta charset=\"utf-8\">\n"
            "<title>CRUCIBLE - %s</title>\n"
            "<!-- Generated by tools/capture/build-cards.py. Do not hand-edit;\n"
            "     rebuild it, or the palette drifts from loop.svg. -->\n"
            "<style>%s</style></head>\n<body>\n%s\n"
            "<div class=\"src\"><b>source:</b> %s</div>\n"
            "</body></html>\n" % (name, CSS, body, source))
    (CARDS / name).write_text(html, encoding="utf-8", newline="")
    print("  wrote cards/%s" % name)


CARDS.mkdir(exist_ok=True)

# ---- N3 · the friction ----------------------------------------------------
card("04-N3-friction.html", """
  <div class="kicker">Before you deploy an agent that holds real permissions</div>
  <div class="steps">
    <div class="step">
      <div class="n">01</div>
      <div class="t">Find the breach</div>
      <div class="d">Today: a person writing prompts by hand until they get
        bored.</div>
    </div>
    <div class="step">
      <div class="n">02</div>
      <div class="t">Patch it</div>
      <div class="d">In English, in a system prompt, where it can be argued
        with.</div>
    </div>
    <div class="step">
      <div class="n">03</div>
      <div class="t">Prove the patch<br>didn't break<br>the business</div>
      <div class="d">There is no regression suite. Last week's fix is untested
        this week.</div>
    </div>
  </div>
  <div class="sub">CRUCIBLE automates that loop &mdash; and
    <b>refuses to ship a fix it cannot prove</b>.</div>
""", "narration N3")

# ---- N5 · the locks -------------------------------------------------------
# "FIVE LOCKS", NEVER "five hashes". Ruling 20 split the fifth into the corpus
# and Part B, frozen together: five locks occupying six fields. "Five hashes"
# is the version a judge reading a bundle can catch.
card("05-N5-locks.html", """
  <div class="kicker">Every bundle carries five locks</div>
  <h1>Committed <span class="hot">before</span><br>the first measurement.</h1>
  <ul>
    <li><b>The gate rule</b> &mdash; what may be promoted, and on what evidence</li>
    <li><b>The frozen target agent</b> &mdash; the thing under test cannot drift</li>
    <li><b>The capability manifest</b> &mdash; every tool, classified, ratified by a human</li>
    <li><b>The Objective Set</b> &mdash; what counts as a breach, decided in advance</li>
    <li><b>The corpus</b> &mdash; the attacks, sealed and hashed</li>
  </ul>
  <div class="sub">The replay tool needs <b>no credentials</b> to check them. It
    re-derives every lock from the bundle bytes.</div>
""", "run_manifest.hash_locks &mdash; five locks over six fields (CONVENTIONS ruling 20)")

# ---- N7 · the efficacy figure --------------------------------------------
card("06-N7-figures.html", """
  <div class="kicker">Two batches &middot; identical configuration &middot; one pre-registered as a replication</div>
  <h1>Attack success,<br>v0 &rarr; <span class="hot">final policy</span></h1>
  <table>
    <tr><th></th><th>v0</th><th>final policy</th></tr>
    <tr class="pool"><td>pooled</td>
      <td>13.5%&nbsp; <span class="den">70/520</span></td>
      <td><span class="arrow">&rarr;</span>&nbsp; 7.7%&nbsp; <span class="den">56/725</span></td></tr>
    <tr><td>measurement batch</td>
      <td>11.8%&nbsp; <span class="den">33/280</span></td>
      <td>5.7%&nbsp; <span class="den">21/366</span></td></tr>
    <tr><td>replication batch</td>
      <td>15.4%&nbsp; <span class="den">37/240</span></td>
      <td>9.7%&nbsp; <span class="den">35/359</span></td></tr>
  </table>
  <div class="sub"><b>The two batches disagree.</b> A replication that
    contradicts the first batch does not retire the first batch &mdash; it
    retires the claim that one batch was enough.<br>
    Reader accepts <b>20 of 20</b> bundles in each. One target agent, k=1 per
    episode, no stability estimate.</div>
""", "docs/design/where-we-stand-2026-08-27.md:189-193 &middot; acceptance from each batch's BATCH-DONE")

# ---- N8 · the negative finding -------------------------------------------
card("07-N8-finding.html", """
  <div class="kicker">The most substantive thing we measured</div>
  <h1>32 rules promoted.<br>13 closed the breach.
      <span class="no">19 were no-ops.</span></h1>
  <div class="sub">The gate promoted every one of those nineteen. It checked
    that the patch was well formed and that benign traffic survived it. <b>It
    never checked that the patch closed the breach it was written for.</b></div>
  <div class="sub">And a rule that <b>over-blocks passes every gate</b> &mdash;
    it stops the attacks, the approval oracle rubber-stamps the benign cases,
    benign pass rate reads perfect, and the agent has been made useless.</div>
  <div class="sub">We found it by recounting a number we had already published.
    It got <b>worse</b>: 58.1% &rarr; 59.4%. A recount that only ever runs when
    the number would improve is not a check.</div>
""", "README.md:95-106 &middot; AUDIT.md C13 &middot; docs/design/gate-noop-measurement-2026-08-25.md")

# ---- N9 · what this is not ------------------------------------------------
card("08-N9-not.html", """
  <div class="kicker">What is not defensible today</div>
  <h1>Eleven days.<br>One person.
      <span class="no">One target agent.</span></h1>
  <ul>
    <li><b>No users.</b> No downloads, no adoption of any kind</li>
    <li><b>Not reviewed, endorsed, or responded to by Google</b> in any way</li>
    <li><b>Single-sample k=1</b>, with no stability estimate</li>
    <li>A held-out attack family exists and is <b>still sealed</b></li>
    <li>The sealed set was reviewed by <b>one person, who is also the builder</b></li>
  </ul>
  <div class="sub">The repository says all of this on its own front page.</div>
""", "README.md &mdash; \"what is not defensible today\"")

# ---- the close ------------------------------------------------------------
card("09-close.html", """
  <div class="kicker">CRUCIBLE</div>
  <h1>Every boundary is a component<br>
      <span class="hot">deliberately blind to something.</span></h1>
  <ul>
    <li>The Coroner writes the autopsy and <b>cannot propose a fix</b> &mdash;
        there is no fix field in its schema</li>
    <li>The Armorer patches in three verbs and <b>has no allow verb</b>, so no
        sequence of patches can widen the blast radius</li>
    <li>The gate <b>reads the bytes back off disk</b> and recomputes the hash
        before it promotes</li>
  </ul>
  <div class="sub">None of that is a prompt. It is <b>a schema, an IAM policy,
    and a grammar</b>.</div>
""", "github.com/emtcmca/crucible &middot; Apache-2.0")

print("done")
