#!/usr/bin/env python3
"""Generate the one-page read-from sheet from the two narration scripts.

DERIVED, NOT COPIED. The spoken lines live in exactly two files and this pulls
them into one place to read from. A hand-made third copy would be a third
source of truth for the only text that gets spoken aloud, and this repository
has published findings about what copies do - the whole point of the sheet is
that it cannot say something the scripts do not.

    python tools/capture/build-read-sheet.py

Writes `docs/design/NARRATION-READ-SHEET.md`.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SOURCES = [
    ROOT / "docs" / "design" / "narration-LOCKED-2026-08-27.md",
    ROOT / "docs" / "design" / "narration-N6-N9-2026-08-30.md",
]
OUT = ROOT / "docs" / "design" / "NARRATION-READ-SHEET.md"

# `## N4 · 0:50-1:35 · architecture ...`  ->  id, timing, description
HEAD = re.compile(r"^##\s+(N\d[a-z]?)\s*·\s*([^·]+)·?\s*(.*)$")
SAY = re.compile(r"^\*\*SAY[^*]*\*\*")
FENCE = "```"


def beats_in(path):
    """(id, timing, blurb, [spoken blocks]) per beat, in file order."""
    lines = path.read_text(encoding="utf-8").splitlines()
    beats, cur, i = [], None, 0
    while i < len(lines):
        line = lines[i]
        m = HEAD.match(line)
        if m:
            cur = {"id": m.group(1).strip(), "timing": m.group(2).strip(),
                   "blurb": m.group(3).strip(), "blocks": []}
            beats.append(cur)
            i += 1
            continue
        if cur is not None and SAY.match(line):
            # EVERY fenced block from here until the next heading or the
            # next SAY marker, not just the first.
            #
            # The first version took one block per marker and silently
            # dropped every continuation after a `*(beat)*` - which is most
            # of N7, N8 and N9. A read sheet missing lines is worse than no
            # read sheet: it looks complete. Prose between blocks is
            # direction and is dropped on purpose; fenced text is spoken.
            i += 1
            while i < len(lines):
                nxt = lines[i]
                if HEAD.match(nxt) or SAY.match(nxt):
                    break
                if nxt.strip() == FENCE:
                    k, body = i + 1, []
                    while k < len(lines) and lines[k].strip() != FENCE:
                        body.append(lines[k])
                        k += 1
                    if k >= len(lines):
                        sys.exit("%s:%d - unterminated fenced block"
                                 % (path.name, i + 1))
                    cur["blocks"].append("\n".join(body).strip("\n"))
                    i = k + 1
                    continue
                i += 1
            if not cur["blocks"]:
                sys.exit("%s - beat %s has a SAY marker and no spoken block"
                         % (path.name, cur["id"]))
            continue
        i += 1
    return beats


def words(text):
    return len(re.findall(r"[A-Za-z0-9'-]+", text))


def main():
    all_beats = []
    for s in SOURCES:
        if not s.exists():
            sys.exit("missing source: %s" % s)
        all_beats += beats_in(s)

    if not all_beats:
        sys.exit("no beats parsed - the heading format changed and this would "
                 "have written an empty sheet")

    total_words = sum(words(b) for beat in all_beats for b in beat["blocks"])

    out = []
    out.append("# NARRATION — every line, in order\n")
    out.append("**GENERATED. Do not edit this file.** It is built from\n"
               "`narration-LOCKED-2026-08-27.md` and\n"
               "`narration-N6-N9-2026-08-30.md` by\n"
               "`tools/capture/build-read-sheet.py`. Edit those; rebuild this.\n"
               "A third hand-made copy of the only text that gets spoken aloud\n"
               "is a third thing that can drift.\n")
    out.append("## Recording rules\n")
    out.append("- **One take per beat.** They cut together, so a fluffed line\n"
               "  costs one beat and its visual retimes around it.\n"
               "- **Two seconds of silence** at the head and tail of every take.\n"
               "- **Sixty seconds of room tone** before you start anything.\n"
               "- Save each take as `audio/<beat id>.wav` — the ids below are\n"
               "  the filenames.\n"
               "- Read at a normal pace. The timings are targets, not\n"
               "  constraints: **the take sets the visual's length**, not the\n"
               "  other way round.\n")
    out.append("- `*(beat)*` between blocks means a pause, not a new file. All\n"
               "  blocks under one heading are **one take**.\n")
    secs = total_words / 150.0 * 60.0
    out.append("**%d beats · %d spoken words · roughly %d:%02d at 150 wpm.**\n"
               % (len(all_beats), total_words, int(secs // 60), int(secs % 60)))

    # THE CAP IS 4:00 AND IT IS THE CONTEST'S, NOT A PREFERENCE. A sheet that
    # reports a total without saying whether it fits is a number nobody acts
    # on, so the arithmetic is done here and the verdict is stated.
    if secs > 237:
        over = secs - 237
        cut = int(total_words - 237 / 60.0 * 150)
        out.append("> ### THIS DOES NOT FIT. Read this before you record.\n"
                   ">\n"
                   "> The cap is **4:00 and it is hard** - the submission form\n"
                   "> rejects longer, and a judge does not watch the overflow.\n"
                   "> Minus the 3s title card that leaves **237s** for speech.\n"
                   ">\n"
                   "> This script runs **%d:%02d**, which is **%d:%02d over**.\n"
                   "> About **%d words** have to come out - roughly %d%% of it.\n"
                   ">\n"
                   "> The per-beat times below are measured, not guessed. The\n"
                   "> longest beats are where the time is: cut there first.\n"
                   "> **Do not try to read it faster.** 988 words in 237s is\n"
                   "> 250 wpm, which is not a pace, it is a mumble.\n"
                   % (int(secs // 60), int(secs % 60),
                      int(over // 60), int(over % 60), cut,
                      round(cut / total_words * 100)))
    else:
        out.append("Fits the 4:00 cap with %ds of headroom for pauses.\n"
                   % int(237 - secs))
    out.append("---\n")

    for b in all_beats:
        n = sum(words(x) for x in b["blocks"])
        out.append("## %s — `audio/%s.wav`\n" % (b["id"], b["id"]))
        out.append("*%s · %s · %d words, ~%ds at 150 wpm*\n"
                   % (b["timing"], b["blurb"] or "—", n, round(n / 150 * 60)))
        for idx, blk in enumerate(b["blocks"]):
            if idx:
                out.append("*(pause — same take)*\n")
            out.append(FENCE + "\n" + blk + "\n" + FENCE + "\n")
        out.append("---\n")

    OUT.write_text("\n".join(out), encoding="utf-8", newline="")
    print("wrote %s" % OUT.relative_to(ROOT))
    for b in all_beats:
        print("  %-4s %2d words  %d block(s)"
              % (b["id"], sum(words(x) for x in b["blocks"]), len(b["blocks"])))
    print("  TOTAL %d words  ~%.1f min at 150 wpm"
          % (total_words, total_words / 150))


if __name__ == "__main__":
    main()
