#!/usr/bin/env bash
# THE ARMORER 403. A live impersonation probe, not a policy grep.
#
# L1-foundation.md section 5 requires "a live 403 from an impersonation probe,
# not a policy grep. The grep is necessary and not sufficient."
#
# WHY A 403 ALONE PROVES NOTHING
# ------------------------------
# A misspelled bucket returns 403. A deleted bucket returns 403. A project the
# caller cannot see returns 403 -- GCS deliberately does not distinguish "you
# may not" from "it is not there", because leaking existence is itself a leak.
# So a screen recording of one red 403 is compatible with the sealed corpus
# sitting wide open at a slightly different path.
#
# This script therefore runs a PAIRED CONTROL. The same object, the same path,
# the same command, three identities:
#
#   crucible-sealed-eval   MUST SUCCEED   proves the path is real and readable
#   crucible-armorer       MUST 403       the G7 boundary
#   crucible-red           MUST 403       the attacker holds no evidence access
#
# The positive control is the half that makes the negatives mean something. If
# sealed-eval also fails, every 403 below is uninformative and the script says
# so rather than reporting a boundary it did not demonstrate.
#
# Run:  bash infra/prove-armorer-403.sh
# Out:  docs/proof/armorer-403.txt
set -uo pipefail

HERE="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck disable=SC1091
. "$HERE/scripts/gcp-env.sh"

OUT="$HERE/docs/proof/armorer-403.txt"
mkdir -p "$HERE/docs/proof"

# MOVED OUT OF families/ 2026-08-22. The canary is not sealed material and it
# has no business sharing a prefix with the sealed instances.
PROBE_OBJECT="$CRUCIBLE_SEALED_BUCKET/_probe/canary.txt"
# The PREFIX form, for the positive control only. See probe() below.
PROBE_PREFIX="$CRUCIBLE_SEALED_BUCKET/_probe/**"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
  echo "CRUCIBLE - the Armorer 403, with its positive control"
  echo "generated by infra/prove-armorer-403.sh"
  echo "project : $CRUCIBLE_PROJECT"
  echo "bucket  : $CRUCIBLE_SEALED_BUCKET"
  echo "object  : $PROBE_OBJECT"
  echo "date    : $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "gcloud  : $(gcloud version 2>/dev/null | head -1)"
  echo ""
  echo "A 403 on its own is not evidence. A misspelled bucket, a deleted bucket,"
  echo "and a project the caller cannot see all return 403, because GCS refuses"
  echo "to distinguish 'you may not' from 'it is not there'. So the same object"
  echo "is read by three identities below, and the FIRST one must SUCCEED."
  echo ""
} > "$TMP"

# --- seed the canary as the operator (the trust root, deliberately noted) -----
printf 'CANARY. Not sealed material. Written by infra/prove-armorer-403.sh so the\n403 probe has a positive control on a real object.\n' \
  | gcloud storage cp - "$PROBE_OBJECT" --quiet >/dev/null 2>&1
SEEDED=$?

{
  if [ "$SEEDED" -eq 0 ]; then
    echo "seed: operator wrote the canary object                       OK"
  else
    echo "seed: operator COULD NOT write the canary object             FAILED"
  fi
  echo ""
} >> "$TMP"

# WHY THE TWO ARMS USE DIFFERENT OPERATIONS. Added 2026-08-22, NEEDS-ERIC item 12.
#
# G7c counts Cloud Audit Log data-access reads on this bucket, and
# infra/holdout_touch.py::classify counts by OPERATION KIND, not by path:
#   * a GRANTED storage.objects.get on a real object  -> CONTENT_READ, COUNTED
#   * storage.objects.list, any storage.buckets.*     -> ENUMERATION, not counted
#   * a DENIED read (granted:false / status 7)        -> not counted
#
# So only one arm can pollute the counter, and the split follows from that:
#   DENY arms keep 'cat'. A denied read is not counted, AND cat is the correct
#     probe for them - it proves objects.get is refused, which IS the boundary.
#     Proving 'list' is refused would prove a weaker and different thing.
#   The ALLOW arm uses 'objects list'. Its job is to prove the probe PATH IS
#     REAL - bucket exists, impersonation works, gcloud functioning - so the
#     403s above it mean something. A listing proves that and is NOT counted.
#     Using cat here would add one counted touch to the sealed bucket EVERY
#     TIME THE GATE PROBES, which under a phase-scoped expected value makes
#     the number depend on how often we probed. Untenable.
#
# WHAT THIS COSTS, stated rather than hidden: the positive control no longer
# proves sealed-eval can read CONTENT, only that it can reach the bucket. That
# grant is evidenced independently - roles/storage.objectViewer bucket-wide
# with no condition, UBLA on, no object ACLs - and by G7c's own canary query,
# which requires a real granted content read in the window before any count is
# trusted. A weaker positive control, chosen over a counter that measures its
# own probing.
probe() {  # probe <sa> <expect: allow|deny>
  local sa="$1" expect="$2" email out rc cmd
  email="$(sa_email "$sa")"
  # An ARRAY, not a string. $PROBE_PREFIX ends in ** and an unquoted string
  # expansion would hand that to pathname expansion against the local
  # filesystem before gcloud ever sees it.
  local -a argv
  if [ "$expect" = "allow" ]; then
    argv=(gcloud storage objects list "$PROBE_PREFIX")
    cmd="gcloud storage objects list $PROBE_PREFIX"
  else
    argv=(gcloud storage cat "$PROBE_OBJECT")
    cmd="gcloud storage cat $PROBE_OBJECT"
  fi
  out="$("${argv[@]}" --impersonate-service-account="$email" 2>&1)"
  rc=$?

  {
    echo "----------------------------------------------------------------------"
    echo "identity : $email"
    echo "expected : $expect"
    echo "command  : $cmd \\"
    echo "             --impersonate-service-account=$email"
    echo "exit     : $rc"
    echo "output   :"
    echo "$out" | sed 's/^/  | /'
  } >> "$TMP"

  # A refusal at the IMPERSONATION layer is not a result about the bucket.
  # The first version of this script matched on the word "permission", and
  # "Permission 'iam.serviceAccounts.getAccessToken' denied" matched it -- so a
  # failure to even become the Armorer was scored PASS - refused. Two convincing
  # green lines about a boundary that had not been tested. Caught only because
  # the positive control failed in the same run and made the pattern visible.
  local impersonation_failed=0
  if echo "$out" | grep -qiE "Failed to impersonate|iam\.serviceAccounts\.getAccessToken"; then
    impersonation_failed=1
  fi

  local verdict
  if [ "$impersonation_failed" -eq 1 ]; then
    verdict="FAIL - refused at the IMPERSONATION layer, not the storage layer. \
The probe never became this identity, so this says NOTHING about the bucket."
  elif [ "$expect" = "allow" ]; then
    if [ "$rc" -eq 0 ]; then verdict="PASS - the path is real and readable"
    else verdict="FAIL - THE CONTROL DID NOT READ. Every 403 below is uninformative."
    fi
  else
    # The deny verdict must name the STORAGE permission specifically. Anything
    # broader credits a refusal from the wrong layer.
    if [ "$rc" -ne 0 ] && echo "$out" | grep -qiE "storage\.objects\.get|403"; then
      verdict="PASS - refused at the storage layer"
    elif [ "$rc" -eq 0 ]; then
      verdict="FAIL - THE READ SUCCEEDED. The boundary does not exist."
    else
      verdict="FAIL - failed for a reason that is not a storage permission denial"
    fi
  fi
  echo "verdict  : $verdict" >> "$TMP"
  echo "" >> "$TMP"
  printf "  %-22s %-6s %s\n" "$sa" "$expect" "$verdict"
  case "$verdict" in PASS*) return 0 ;; *) return 1 ;; esac
}

echo "probing $PROBE_OBJECT"
FAILS=0
probe "$SA_SEALED_EVAL" allow || FAILS=$((FAILS + 1))
probe "$SA_ARMORER"     deny  || FAILS=$((FAILS + 1))
probe "$SA_RED"         deny  || FAILS=$((FAILS + 1))

{
  echo "======================================================================"
  if [ "$FAILS" -eq 0 ]; then
    echo "RESULT: 3/3. The positive control read the object; the Armorer and the"
    echo "Red Strategist were refused on the identical path with the identical"
    echo "command. The boundary is IAM, not convention."
  else
    echo "RESULT: $FAILS of 3 failed. DO NOT PRESENT THIS AS A PROOF."
  fi
  echo ""
  echo "What this does NOT show, stated so the claim stays exactly true:"
  echo "  * The operator (a human with roles/owner) can read everything here."
  echo "    You are the trust root and no control defends against you."
  echo "    data-spec.md 4.1 row 12 says so deliberately."
  echo "  * The canary is not sealed material. It was written by this script."
  echo "  * Impersonation required roles/iam.serviceAccountTokenCreator granted"
  echo "    to the operator ON THOSE SERVICE ACCOUNTS. That grant lets the"
  echo "    operator ACT AS them; it does not give them any new access."
} >> "$TMP"

cp "$TMP" "$OUT"

# Postcondition. The file on disk is the artifact, not this script's exit code.
echo ""
echo "wrote $OUT ($(wc -c < "$OUT") bytes, $(wc -l < "$OUT") lines)"
grep -E "^RESULT" "$OUT"
exit "$([ "$FAILS" -eq 0 ] && echo 0 || echo 1)"
