#!/usr/bin/env bash
# THE ARMORER 403. A live impersonation probe, not a policy grep.
#
# L1-foundation.md section 5 requires "a live 403 from an impersonation probe,
# not a policy grep. The grep is necessary and not sufficient."
#
# WHY A 403 ALONE PROVES NOTHING
# ------------------------------
# A misspelled bucket returns 403. A deleted bucket returns 403. A project the
# caller cannot see returns 403 -- GCS deliberately does not distinguish "you
# may not" from "it is not there", because leaking existence is itself a leak.
# So a screen recording of one red 403 is compatible with the sealed corpus
# sitting wide open at a slightly different path.
#
# This script therefore runs a PAIRED CONTROL. The same object, the same path,
# the same command, three identities:
#
#   crucible-sealed-eval   MUST SUCCEED   proves the path is real and readable
#   crucible-armorer       MUST 403       the G7 boundary
#   crucible-red           MUST 403       the attacker holds no evidence access
#
# The positive control is the half that makes the negatives mean something. If
# sealed-eval also fails, every 403 below is uninformative and the script says
# so rather than reporting a boundary it did not demonstrate.
#
# Run:  bash infra/prove-armorer-403.sh
# Out:  docs/proof/armorer-403.txt
set -uo pipefail

HERE="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck disable=SC1091
. "$HERE/scripts/gcp-env.sh"

OUT="$HERE/docs/proof/armorer-403.txt"
mkdir -p "$HERE/docs/proof"

PROBE_OBJECT="$CRUCIBLE_SEALED_BUCKET/families/_probe/canary.txt"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
  echo "CRUCIBLE - the Armorer 403, with its positive control"
  echo "generated by infra/prove-armorer-403.sh"
  echo "project : $CRUCIBLE_PROJECT"
  echo "bucket  : $CRUCIBLE_SEALED_BUCKET"
  echo "object  : $PROBE_OBJECT"
  echo "date    : $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "gcloud  : $(gcloud version 2>/dev/null | head -1)"
  echo ""
  echo "A 403 on its own is not evidence. A misspelled bucket, a deleted bucket,"
  echo "and a project the caller cannot see all return 403, because GCS refuses"
  echo "to distinguish 'you may not' from 'it is not there'. So the same object"
  echo "is read by three identities below, and the FIRST one must SUCCEED."
  echo ""
} > "$TMP"

# --- seed the canary as the operator (the trust root, deliberately noted) -----
printf 'CANARY. Not sealed material. Written by infra/prove-armorer-403.sh so the\n403 probe has a positive control on a real object.\n' \
  | gcloud storage cp - "$PROBE_OBJECT" --quiet >/dev/null 2>&1
SEEDED=$?

{
  if [ "$SEEDED" -eq 0 ]; then
    echo "seed: operator wrote the canary object                       OK"
  else
    echo "seed: operator COULD NOT write the canary object             FAILED"
  fi
  echo ""
} >> "$TMP"

probe() {  # probe <sa> <expect: allow|deny>
  local sa="$1" expect="$2" email out rc
  email="$(sa_email "$sa")"
  out="$(gcloud storage cat "$PROBE_OBJECT" \
          --impersonate-service-account="$email" 2>&1)"
  rc=$?

  {
    echo "----------------------------------------------------------------------"
    echo "identity : $email"
    echo "expected : $expect"
    echo "command  : gcloud storage cat $PROBE_OBJECT \\"
    echo "             --impersonate-service-account=$email"
    echo "exit     : $rc"
    echo "output   :"
    echo "$out" | sed 's/^/  | /'
  } >> "$TMP"

  # A refusal at the IMPERSONATION layer is not a result about the bucket.
  # The first version of this script matched on the word "permission", and
  # "Permission 'iam.serviceAccounts.getAccessToken' denied" matched it -- so a
  # failure to even become the Armorer was scored PASS - refused. Two convincing
  # green lines about a boundary that had not been tested. Caught only because
  # the positive control failed in the same run and made the pattern visible.
  local impersonation_failed=0
  if echo "$out" | grep -qiE "Failed to impersonate|iam\.serviceAccounts\.getAccessToken"; then
    impersonation_failed=1
  fi

  local verdict
  if [ "$impersonation_failed" -eq 1 ]; then
    verdict="FAIL - refused at the IMPERSONATION layer, not the storage layer. \
The probe never became this identity, so this says NOTHING about the bucket."
  elif [ "$expect" = "allow" ]; then
    if [ "$rc" -eq 0 ]; then verdict="PASS - the path is real and readable"
    else verdict="FAIL - THE CONTROL DID NOT READ. Every 403 below is uninformative."
    fi
  else
    # The deny verdict must name the STORAGE permission specifically. Anything
    # broader credits a refusal from the wrong layer.
    if [ "$rc" -ne 0 ] && echo "$out" | grep -qiE "storage\.objects\.get|403"; then
      verdict="PASS - refused at the storage layer"
    elif [ "$rc" -eq 0 ]; then
      verdict="FAIL - THE READ SUCCEEDED. The boundary does not exist."
    else
      verdict="FAIL - failed for a reason that is not a storage permission denial"
    fi
  fi
  echo "verdict  : $verdict" >> "$TMP"
  echo "" >> "$TMP"
  printf "  %-22s %-6s %s\n" "$sa" "$expect" "$verdict"
  case "$verdict" in PASS*) return 0 ;; *) return 1 ;; esac
}

echo "probing $PROBE_OBJECT"
FAILS=0
probe "$SA_SEALED_EVAL" allow || FAILS=$((FAILS + 1))
probe "$SA_ARMORER"     deny  || FAILS=$((FAILS + 1))
probe "$SA_RED"         deny  || FAILS=$((FAILS + 1))

{
  echo "======================================================================"
  if [ "$FAILS" -eq 0 ]; then
    echo "RESULT: 3/3. The positive control read the object; the Armorer and the"
    echo "Red Strategist were refused on the identical path with the identical"
    echo "command. The boundary is IAM, not convention."
  else
    echo "RESULT: $FAILS of 3 failed. DO NOT PRESENT THIS AS A PROOF."
  fi
  echo ""
  echo "What this does NOT show, stated so the claim stays exactly true:"
  echo "  * The operator (a human with roles/owner) can read everything here."
  echo "    You are the trust root and no control defends against you."
  echo "    data-spec.md 4.1 row 12 says so deliberately."
  echo "  * The canary is not sealed material. It was written by this script."
  echo "  * Impersonation required roles/iam.serviceAccountTokenCreator granted"
  echo "    to the operator ON THOSE SERVICE ACCOUNTS. That grant lets the"
  echo "    operator ACT AS them; it does not give them any new access."
} >> "$TMP"

cp "$TMP" "$OUT"

# Postcondition. The file on disk is the artifact, not this script's exit code.
echo ""
echo "wrote $OUT ($(wc -c < "$OUT") bytes, $(wc -l < "$OUT") lines)"
grep -E "^RESULT" "$OUT"
exit "$([ "$FAILS" -eq 0 ] && echo 0 || echo 1)"
