"""Assemble the Cloud Run deploy package. Run before `adk deploy cloud_run`.

WHY THIS EXISTS, AND IT IS NOT A CONVENIENCE.

`adk deploy cloud_run <AGENT_PATH>` does exactly one thing with the source:

    cli_deploy.py:702   shutil.copytree(agent_folder, <temp>/agents/<basename>)
    cli_deploy.py:96    COPY "agents/<name>/" "/app/agents/<name>/"

It copies THE AGENT FOLDER AND NOTHING ELSE. Anything the agent imports from
outside that folder does not exist in the container. `deploy/refund_agent/agent.py`
did `from target.refund_agent.agent import build_agent`, which resolves fine on
this machine and raises `ModuleNotFoundError: No module named 'target'` at
container start.

That failure is the dangerous shape rather than the loud one. The image builds,
Cloud Run reports the revision healthy, and the deploy log is clean - the agent
simply never loads, and `/list-apps` comes back empty. A deploy that looks
successful and serves nothing is precisely what postcondition 2 in RUNBOOK.md
exists to catch, and it should not have to.

THE SECOND DEFECT THIS FIXES. `target/refund_agent/tools.py` holds `_LEDGER = None`
until `bind_backends()` is called, and `_ledger()` raises `BackendsNotBoundError`
otherwise - deliberately loud, so that an unbound tool cannot produce an episode in
which nothing happened and nothing failed. Nothing in the old shim bound it. Every
tool call in the deployed agent would have raised, and postcondition 3 wants an
`execute_tool` span from a tool call that actually ran.

WHY VENDOR RATHER THAN EDIT THE TARGET. `freeze.py::runtime_source_hashes()`
asserts `RUNTIME_MODULES` against the directory contents in BOTH directions: a
`.py` file in the target package that is not declared raises, and a declared one
that is missing raises. There is no way to add a deploy entry point inside the
frozen package. Nor should there be - after D3 on 2026-08-22 that directory cannot
change without voiding the run, and deployment scaffolding must stay editable.

WHY THE COPY IS SAFE. It is DERIVED AND VERIFIED, not authored. Every staged byte
is re-read from disk after the copy and compared by SHA-256 against its source, and
a mismatch is a hard refusal rather than a warning. `target/` stays the single
source of truth; the stage is a build artifact, gitignored, rebuilt every deploy.
If this script ever silently let the two drift, the Cloud Run demo would stop being
evidence about the agent we measure, which is the only reason to deploy it at all.
"""

import hashlib
import pathlib
import shutil
import sys

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parent
SOURCE = REPO / "target" / "refund_agent"
STAGE = HERE / ".stage" / "refund_agent"
VENDOR = STAGE / "_target"

# Not copied. `__pycache__` is machine-local build output; copying it would put
# this machine's .pyc files in the image and make the staged tree unverifiable
# against the source, since there is nothing to compare them to.
IGNORE = shutil.ignore_patterns("__pycache__", "*.pyc")

SHIM = '''"""Cloud Run entry point. GENERATED by `deploy/build-stage.py` - do not edit.

Edit the generator, not this file. It is rebuilt from scratch on every deploy and
any change made here is lost without being noticed.

`_target/` is a verified byte-identical copy of `target/refund_agent/`, vendored
because `adk deploy cloud_run` copies only the agent folder into the container.
The agent constructed below is built by the same `build_agent()` the harness
calls, from the same bytes, so the deployed agent and the measured agent are the
same object.
"""

from ._target.agent import build_agent
from ._target import tools as _tools
from ._target.simulated_system_of_record import (
    SimulatedSystemOfRecord, seed_demo_ledger)

# The tools refuse to run unbound (`BackendsNotBoundError`), on purpose. This is
# the same seeded world the three demo transcripts run against, with `as_of`
# defaulting to the frozen `DEMO_AS_OF` rather than the system clock - a target
# that read the wall clock would be non-replayable.
#
# It is a SIMULATED system of record. The deployed service moves no real money and
# mails no real address: every seeded address is `.invalid` per RFC 2606.
_tools.bind_backends(seed_demo_ledger(SimulatedSystemOfRecord()))

root_agent = build_agent()
'''


# Installed into the container by the Dockerfile ADK generates. Nothing else puts
# it there.
#
# WHY THIS FILE EXISTS. `adk deploy cloud_run --trace_to_cloud` fails at container
# START, not at build, with:
#
#     File "google/adk/cli/fast_api.py", line 563, in get_fast_api_app
#         from opentelemetry.exporter.cloud_trace import CloudTraceSpanExporter
#     ModuleNotFoundError: No module named 'opentelemetry.exporter'
#
# The generated Dockerfile runs `pip install google-adk==2.1.0` and nothing more.
# The Cloud Trace exporter is not a dependency of base `google-adk`, and the
# generated image installs agent dependencies ONLY if the agent folder carries a
# `requirements.txt` (cli_deploy.py:703-708). So the flag is accepted, the build
# succeeds, the image pushes, and the revision dies on its first import - a
# failure that costs a full container build to discover.
#
# Pinned, like every other version in this build. `--trace_to_cloud` is not
# decoration: postcondition 3 in `deploy/RUNBOOK.md` wants an `execute_tool` span
# carrying `gen_ai.agent.name` visible in Trace Explorer, and that span is the
# cleanest on-camera proof that the backend runs on Google Cloud rather than on a
# laptop.
REQUIREMENTS = """opentelemetry-exporter-gcp-trace==1.15.0
"""


def _sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main():
    if not SOURCE.is_dir():
        sys.exit("E_NO_SOURCE: %s does not exist" % SOURCE)

    if STAGE.parent.exists():
        shutil.rmtree(STAGE.parent)
    VENDOR.parent.mkdir(parents=True)

    shutil.copytree(SOURCE, VENDOR, ignore=IGNORE)
    (STAGE / "__init__.py").write_text("", encoding="utf-8")
    (STAGE / "agent.py").write_text(SHIM, encoding="utf-8", newline="\n")
    (STAGE / "requirements.txt").write_text(
        REQUIREMENTS, encoding="utf-8", newline="\n")

    # Verify. Re-read both sides from disk rather than trusting copytree's return.
    src_files = sorted(
        p for p in SOURCE.rglob("*")
        if p.is_file() and "__pycache__" not in p.parts and p.suffix != ".pyc")
    staged_files = sorted(
        p for p in VENDOR.rglob("*") if p.is_file())

    src_rel = {p.relative_to(SOURCE).as_posix() for p in src_files}
    stage_rel = {p.relative_to(VENDOR).as_posix() for p in staged_files}

    if src_rel != stage_rel:
        missing = sorted(src_rel - stage_rel)
        extra = sorted(stage_rel - src_rel)
        sys.exit("E_STAGE_FILE_SET: missing=%s extra=%s" % (missing, extra))

    mismatched = []
    for rel in sorted(src_rel):
        a, b = _sha(SOURCE / rel), _sha(VENDOR / rel)
        if a != b:
            mismatched.append((rel, a[:16], b[:16]))
    if mismatched:
        for rel, a, b in mismatched:
            print("MISMATCH %s source=%s staged=%s" % (rel, a, b))
        sys.exit("E_STAGE_HASH_MISMATCH: the stage is not a faithful copy")

    print("staged %d files, all byte-identical to %s" % (len(src_rel), SOURCE))
    for rel in sorted(src_rel):
        print("  %s  %s" % (_sha(VENDOR / rel)[:16], rel))
    print("generated: __init__.py, agent.py, requirements.txt")
    print("AGENT_PATH: %s" % STAGE)


if __name__ == "__main__":
    main()
