#!/usr/bin/env python3
"""probe-g7-g8.py - run G7 and G8 against the live project and write the proof.

READ-ONLY. Every gcloud call this makes is `get-iam-policy`, `describe`, or
`objects list`. It creates nothing, deletes nothing, and binds nothing. It does
not promote a policy version either: it calls `RealGate.preflight()`, which is
the assertion half, and stops there.

WHY THIS EXISTS SEPARATELY FROM `infra/verify_iam.py`
-----------------------------------------------------
`verify_iam.py` asserts the IAM documents. It does not run the G7a impersonation
probe, and it does not evaluate G7c. Those two are the assertions that are not
about what a policy document says but about what an identity can actually do,
and they are where the two live gaps turned out to be. This runs the whole of
G7 and G8 as `crucible.conductor.real_gate` will run them inside a campaign, so
the artifact on disk is the same evaluation the loop performs and not a
second implementation of it.

  python scripts/probe-g7-g8.py
  -> docs/proof/L3-real-gate-G7-G8-YYYY-MM-DD.txt
"""

import datetime
import pathlib
import subprocess
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from crucible.conductor import real_gate as rg     # noqa: E402


def main():
    day = datetime.date.today().isoformat()
    out_path = REPO / "docs" / "proof" / ("L3-real-gate-G7-G8-%s.txt" % day)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    gate = rg.RealGate(
        ledger=None, run_id="probe", blob_writer=None, blob_reader=None,
        repo_root=REPO, holdout_touch=None)
    findings = gate.preflight()
    bad = [f for f in findings if f["status"] != rg.PASS]

    lines = [
        "CRUCIBLE - G7 (SEAL INTEGRITY) and G8 (NON-SELF-APPROVAL), evaluated",
        "generated by scripts/probe-g7-g8.py  (READ-ONLY: no gcloud call here",
        "creates, deletes, or binds anything)",
        "project  : %s" % gate.env["CRUCIBLE_PROJECT"],
        "promoter : %s   <- read from scripts/gcp-env.sh, not typed here"
        % gate.promoted_by,
        "date     : %sZ" % datetime.datetime.utcnow().isoformat(timespec="seconds"),
        "gcloud   : %s" % _gcloud_version(),
        "",
        "Until this ran, the campaign's gate hook was `lambda c, r: True` - a",
        "constant function that returns PROMOTE for every candidate having",
        "inspected nothing. G7 and G8 are the two gates whose failure mode is",
        "RUN INVALID, and neither had ever been evaluated against anything.",
        "",
        rg.render(findings),
        "",
        "=" * 70,
        "%d assertions, %d PASS, %d not PASS"
        % (len(findings), len(findings) - len(bad), len(bad)),
        "",
    ]
    if bad:
        lines += [
            "NOT A CLEAN RESULT, AND THAT IS THE POINT OF RUNNING IT.",
            "An UNEVALUABLE assertion is not a pass. G7's contract",
            "(contracts/gate_rule.v1.yaml) sends `absent_or_unevaluable` to",
            "RUN INVALID precisely so a check that measured nothing cannot be",
            "scored as a check that held.",
            "",
        ]
    lines += [
        "What this does NOT show, stated so the claim stays exactly true:",
        "  * The operator (a human with roles/owner) can read everything here.",
        "    You are the trust root and no control defends against you.",
        "  * Nothing was promoted. This is preflight only; the write path with",
        "    its read-back assertion is exercised by tests/test_real_gate.py",
        "    against a local blob store, and has NEVER run against GCS.",
        "  * A PASS on an IAM document is a snapshot, not a guarantee. The",
        "    whole point of re-asserting every run is that a grant made later",
        "    is invisible to a check that ran earlier.",
    ]
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    # Postcondition, not the exit code: the file on disk is the artifact.
    print(out_path.read_text(encoding="utf-8"))
    print("wrote %s (%d bytes)" % (out_path, out_path.stat().st_size))
    return 1 if bad else 0


def _gcloud_version():
    try:
        exe = rg.verify_iam._gcloud_exe()            # noqa: SLF001
        return subprocess.run([exe, "version"], capture_output=True,
                              text=True).stdout.splitlines()[0]
    except Exception as e:                           # noqa: BLE001
        return "unavailable: %s" % e


if __name__ == "__main__":
    raise SystemExit(main())
